[project]
name = "cohortly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.7",
    "django-allauth[socialaccount]>=65.18.0",
    "django-environ>=0.14.0",
]

[dependency-groups]
dev = [
    "djangofmt>=0.2.12",
]
