# Generated by Django 6.0.7 on 2026-08-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='topic',
            new_name='topics',
        ),
    ]
