# Generated by Django 6.0.7 on 2026-08-22 06:59

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_rename_topic_question_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=markdownx.models.MarkdownxField(help_text='Format your text using <a href="https://www.markdownguide.org/cheat-sheet/">Markdown Syntax</a> to easily add bolding, italics, lists, and links.', max_length=30000),
        ),
    ]
