# Generated by Django 6.0.7 on 2026-08-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_alter_question_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='marked_as_solution',
            field=models.BooleanField(default=False),
        ),
    ]
