# Generated by Django 6.0.7 on 2026-07-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_topics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
