# Generated by Django 6.0.7 on 2026-08-20 14:21

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_topic_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
