# Generated by Django 6.0.7 on 2026-08-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_topic_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='topic',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
