# Generated by Django 6.0.7 on 2026-08-22 06:55

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_alter_topic_options_topic_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Format your text using <a href="https://www.markdownguide.org/cheat-sheet/">Markdown Syntax</a> to easily add bolding, italics, lists, and links.'),
        ),
    ]
