# Generated by Django 6.0.7 on 2026-08-29 12:15

import tutoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_alter_topic_description'),
        ('tutoring', '0003_session_check_end_time_after_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(validators=[tutoring.models.validate_not_in_past]),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(validators=[tutoring.models.validate_not_in_past]),
        ),
        migrations.AlterConstraint(
            model_name='session',
            name='check_end_time_after_start_time',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='check_end_time_after_start_time', violation_error_message='The end time must occur after the start time'),
        ),
    ]
