# Generated by Django 6.0.7 on 2026-08-29 12:15

import django.core.validators
import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Pending scan'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Scan error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='resources/', validators=[resources.models.validate_file_size, resources.models.validate_pdf, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Unsupported file type, the file must be a valid PDF document.')]),
        ),
    ]
